config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :timelines do
    resources :steps, shallow: true do
      member do
        post 'up'
        post 'down'
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :steps
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :timeline
  belongs_to :category

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  acts_as_list scope: :timeline

  attr_accessor :distance_with_next_step


  def lat_lng
    "#{latitude}, #{longitude}"
  end

  def to_lat_lng
    [latitude, longitude]
  end
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  belongs_to :user
  has_many :steps, -> { order(position: :asc) }, dependent: :destroy

  geocoded_by :destination
  after_validation :geocode, if: :destination_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :timelines, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!
  def home
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  before_action :find_timeline, only: [:create]
  before_action :find_step, only: [:show, :edit, :update, :destroy, :up, :down]
  def index
    @steps = Step.all
    @markers = Gmaps4rails.build_markers(@steps) do |step, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  def show
    @step = Step.find(params[:id])
    @step_coordinates = { lat: @flat.lat, lng: @flat.lng }
  end

  def new
    @step = Step.new
  end

  def create
    @step = @timeline.steps.new(step_params)
    @step.save
    respond_to do |format|
      format.js
    end
  end

  def edit
  end

  def update
    @step.update(step_params)
  end

  def destroy
    @step.destroy
    respond_to do |format|
      format.js
    end
  end

  def up
    @moved = @step.move_higher
    respond_to do |format|
      format.js
    end
  end

  def down
    @moved = @step.move_lower
    respond_to do |format|
      format.js
    end
  end

  private

  def step_params
    params.require(:step).permit(:address, :title, :scheduled_at, :position, :category_id, :latitude, :longitude)
  end

  def find_step
    @step = Step.find(params[:id])
  end

  def find_timeline
    @timeline = Timeline.find(params[:timeline_id])
  end

end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def index
    @timelines = Timeline.all
    if params[:destination]
      @timelines = Step.near(params[:destination], 300).map(&:timeline).uniq
    end
  end

  def show
    @timeline = Timeline.find(params[:id])
    @timeline.steps.each do |step|
      unless step.last?
        step.distance_with_next_step = Geocoder::Calculations.distance_between(step.to_lat_lng, step.lower_item.to_lat_lng)
      end
    end
    @markers = Gmaps4rails.build_markers(@timeline.steps) do |step, marker|
      marker.lat step.latitude
      marker.lng step.longitude
    end
  end

  def new
    @timeline = current_user.timelines.create(destination: params[:destination])
    redirect_to edit_timeline_path(@timeline)
  end

  def edit
    @step = Step.new
    @timeline = current_user.timelines.find(params[:id])
  end

  def update
    @timeline = current_user.timelines.find(params[:id])
    @timeline.update(timeline_params)
    redirect_to edit_timeline_path(@timeline)
  end

  def destroy
    @timeline = current_user.timelines.find(params[:id])
    @timeline.destroy
  end

  private

  def timeline_params
    params.require(:timeline).permit(:title, :start_date, :end_date, :destination, :budget, :latitude, :longitude)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def editable?
    controller.action_name == "edit" or controller.action_name == "create"
  end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roaddy</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyBWWIcM5rreKKP71Q82e4OEakHu_omStvA" %>
    <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(<%= image_url 'background.jpg' %>)">
  <div class="banner-content">
    <h1 class="bigtitle">Roaddy</h1>
    <p>Inspired people for inspiring trips</p>
    <%= form_tag timelines_path, method: "get", class: "navbar-wagon-search" do %>
      <%= text_field_tag "destination", nil, placeholder: "Où va-t'on ?", class: "navbar-wagon-search-input", id: "autocomplete" %>
      <%= button_tag type: "submit", class: "navbar-wagon-search-btn" do %>
        <i class="fa fa-search"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%#= link_to "Créer un voyage", new_timeline_path(), class: "navbar-wagon-item btn-perso" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/steps/_form.html.erb
<div class="step-wrapper">
  <div class="step-waypoint step-add">
  </div>
  <div class="step step-form">
    <h4 class="text-center">Ajouter une étape</h4>
    <%= simple_form_for [timeline, step], remote: true do |f| %>
      <%= f.input :title, label: false, placeholder: "Titre de l'étape", input_html: { class: "input-lg" }  %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.input :address, input_html: { id: "autocomplete" }, label: false, placeholder: "Indiquez un lieu" %>
          <%#= f.input :scheduled_at, label: false %>
        </div>
        <div class="col-sm-6">
          <%= f.association :category, label: false, prompt: "Catégorie" %>
        </div>
      </div>
      <%= f.submit "Ajouter cette étape", class: "btn btn-default btn-block" %>
    <% end %>
  </div>
</div>

app/views/steps/_show.html.erb
<div class="step-wrapper">
  <div class="step-waypoint">
  </div>
  <div class="step" id="step-<%= step.id %>">
    <% if editable? %>
      <div class="step-position">
        <%= link_to up_step_path(step), method: :post, remote: true, class: "step-up" do %>
          <i class="fa fa-angle-up"></i>
        <% end %>
        <%= link_to down_step_path(step), method: :post, remote: true, class: "step-down" do %>
          <i class="fa fa-angle-down"></i>
        <% end %>
      </div>
    <% end %>
    <div class="step-content">
      <h4>
        <%= step.title %>
        <%= step.title %>
        <% if step.category.present? %>
          <small>
            <span class="label label-primary"><%= step.category.name %></span>
          </small>
        <% end %>
      </h4>
      <p class="text-muted"><%= step.address %></p>
    </div>
    <% if editable? %>
      <div class="step-actions">
        <%= link_to step_path(step), method: :delete, remote: true, data: { confirm: "Êtes-vous sûr de vouloir supprimer cette étape ?"} do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <% unless editable? or step.last? %>
  <p class="step-distance"><span><i class="fa fa-road"></i> <%= step.distance_with_next_step.round(2) if step.distance_with_next_step %> km</span></p>
  <% end %>
</div>

app/views/steps/create.js.erb
$('#timeline').append("<%= j render 'steps/show', step: @step %>");
<%= render 'timelines/map', timeline: @step.timeline %>

app/views/steps/destroy.js.erb
$('#step-<%= @step.id %>').closest('.step-wrapper').remove();
<%= render 'timelines/map', timeline: @step.timeline %>

app/views/steps/down.js.erb
<% if @moved %>
  $currentStep = $('#step-<%= @step.id %>').closest('.step-wrapper');
  $currentStep.insertAfter($currentStep.next());
  <%= render 'timelines/map', timeline: @step.timeline %>
<% end %>

app/views/steps/up.js.erb
<% if @moved %>
  $currentStep = $('#step-<%= @step.id %>').closest('.step-wrapper');
  $currentStep.insertBefore($currentStep.prev());
  <%= render 'timelines/map', timeline: @step.timeline %>
<% end %>

app/views/timelines/_form.html.erb
<%= simple_form_for @timeline do |f| %>
  <%= f.input :title, label: "Nom du voyage", placeholder: "Titre du voyage", input_html: { class: "input-lg" } %>
  <div class="row">
    <div class="col-xs-4">
      <%= f.input :budget, label: "Budget (€)", placeholder: "optionnel"%>
    </div>
    <div class="col-xs-4">
      <%= f.input :start_date, label: "Début", as: :string, input_html: { class: "datepicker" } %>
    </div>
    <div class="col-xs-4">
      <%= f.input :end_date, label: "Fin", as: :string, input_html: { class: "datepicker" } %>
    </div>
  </div>
  <%= f.submit "Enregistrer la timeline", class: "btn btn-primary btn-block" %>
<% end %>

app/views/timelines/_map.js.erb
<% if timeline.steps.any? %>
  var directionsDisplay = new google.maps.DirectionsRenderer();
  var directionsService = new google.maps.DirectionsService();

  function calcRoute() {
    var origin      = new google.maps.LatLng(<%= timeline.steps.first.lat_lng %>);
    var destination = new google.maps.LatLng(<%= timeline.steps.last.lat_lng %>);

    var request = {
        origin: origin,
        <% if timeline.steps.size > 2 %>
          waypoints: [
            <% timeline.steps[1..-2].each do |step| %>
              {
                location: new google.maps.LatLng(<%= step.lat_lng %>),
                stopover: true
              },
            <% end %>
          ],
        <% end %>
        destination: destination,
        travelMode:  google.maps.TravelMode.WALKING
    };
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
      }
    });
  }

  calcRoute();

  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'directions'}}, function(){
    directionsDisplay.setMap(handler.getMap());
  });
<% else %>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('directions'), {
      center: {lat: <%= timeline.latitude %>, lng: <%= timeline.longitude %>},
      zoom: 12
    });
  }
  initMap();
<% end %>

app/views/timelines/edit.html.erb
<div class="flex fixed">
  <div class="timeline-content">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
      <li role="presentation" class="active">
        <a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">
          <i class="fa fa-cogs"></i> Paramètres
        </a>
      </li>
      <li role="presentation">
        <a href="#steps" aria-controls="steps" role="tab" data-toggle="tab">
          <i class="fa fa-map-marker"></i> Étapes
        </a>
      </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="settings">
        <h3 class="tab-title">
          Paramètres de mon voyage sur <%= @timeline.destination %>
        </h3>
        <%= render "timelines/form", timeline: @timeline %>
      </div>
      <div role="tabpanel" class="tab-pane" id="steps">
        <h3 class="tab-title">
          Les étapes de mon voyage
        </h3>
        <div id="timeline" class="step-edit">
          <% @timeline.steps.each do |step| %>
            <%= render "steps/show", step: step %>
          <% end %>
        </div>

        <%= render "steps/form", timeline: @timeline, step: @step %>
      </div>
    </div>
  </div>
  <div class="timeline-map">
    <div class="map" id="directions" style='width: 100%; height: 100%;'></div>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>
    <%= render "timelines/map.js.erb", timeline: @timeline %>
  </script>
<% end %>

app/views/timelines/index.html.erb
<h3 class="text-center itineraire-title">Itinéraires autour de <%= params[:destination] %></h3>

<p class="text-center">
  <%= link_to "Nouvel itinéraire sur #{params[:destination]}", new_timeline_path() + "?destination=#{params[:destination]}", class: "btn btn-primary btn-sm"  %>
</p>

<hr>

<% unless @timelines.any? %>
  <h3 class="text-muted text-center">
    <i class="fa fa-cloud motorcycle-smoke"></i>
    <i class="fa fa-motorcycle motorcycle-club"></i>
    <br>
    <em class="slim">
      Pas d'itinéraire pour le moment, voulez vous en créer un ?
    </em>
  </h3>
<% end %>
<% @timelines.each do |timeline| %>
  <div class="infotimeline">
    <span><h6 class="destination-title">- <%= timeline.title %></h6></span>
    <span><h6 class="startdate">Début : <%= timeline.start_date.strftime('%v') if timeline.start_date %></h6></span>
    <span><h6 class="enddate">Fin : <%= timeline.end_date.strftime('%v') if timeline.end_date %></h6></span>
    <h5><%= link_to "Détails", timeline_path(timeline),class: "btn-perso" %></h5>
  </div>
  <hr>
<% end %>

app/views/timelines/show.html.erb
<div class="flex fixed">
  <div class="timeline-content">
    <h3 class="text-center">
      <%= @timeline.title %>
      <small>
        <%= link_to "Modifier", edit_timeline_path(@timeline), class: "btn btn-default btn-xs" %>
      </small>
    </h3>
    <div class="row text-center timeline-infos">
      <div class="col-xs-4">
        <strong>Début</strong>
        <h3 class="text-muted slim"><%= l(@timeline.start_date, format: :short) if @timeline.start_date %></h3>
      </div>
      <div class="col-xs-4">
        <strong>Fin</strong>
        <h3 class="text-muted slim"><%= l(@timeline.end_date, format: :short) if @timeline.end_date %></h3>
      </div>
      <div class="col-xs-4">
        <strong>Budget</strong>
        <h3 class="text-muted slim"><%= @timeline.budget %> €</h3>
      </div>
    </div>
    <div id="timeline" class="step-show">
      <% @timeline.steps.each do |step| %>
        <%= render "steps/show", step: step %>
      <% end %>
    </div>
  </div>
  <div class="timeline-map">
    <div class="map" id="directions" style='width: 100%; height: 100%;'></div>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>
    <%= render "timelines/map.js.erb", timeline: @timeline %>
  </script>
<% end %>